mutation ApproveMaxENJ($identityId: Int) {
  transaction: CreateEnjinRequest(
    identity_id: $identityId
    type: APPROVE
    approve_enj_data: {
      value: -1
    }
  ) {
    id
    encodedData
  }
}
