mutation CompleteTrade($identityId: Int!, $tradeId: String!) {
  result: CreateEnjinRequest(identity_id: $identityId, type: COMPLETE_TRADE, complete_trade_data: { trade_id: $tradeId }) {
    id
    encoded_data
    state
  }
}
