mutation CreateTrade($appId: Int!, $askingTokenId: String!, $askingValue: Int!, $offeringTokenId: String!, $offeringValue: Int!, $secondPartyIdentityId: Int!) {
  result: CreateEnjinRequest(type: CREATE_TRADE, appId: $appId, create_trade_data: {
    asking_tokens: [
      {
        id: $askingTokenId,
        value: $askingValue
      }
    ],
    offering_tokens: [
      {
        id: $offeringTokenId,
        value: $offeringValue
      }
    ],
    second_party_identity_id: $secondPartyIdentityId
  }) {
    id
    encodedData
    state
  }
}
