query Items($identityId: Int!) {
  identities: EnjinIdentities(id: $identityId) {
    tokens {
      id
      index
      name
      appId
      creator
      totalSupply
      reserve
      circulatingSupply
      supplyModel
      meltValue
      meltFeeRatio
      meltFeeMaxRatio
      transferable
      transferFeeSettings {
        type
        token_id
        value
      }
      nonFungible
      icon
    }
  }
}
