query Login($email: String!, $password: String!) {
  user: EnjinOauth(email: $email, password: $password) {
    id
    name
    email
    accessTokens
    identities {
      id
      appId
      ethAddress
    }
  }
}
