query Login($email:String!, $password:String!) {
  results: EnjinOauth(email: $email, password: $password) {
    id
    access_tokens
    roles {
      name
    }
    identities {
      id
      app_id
      ethereum_address
    }
  }
}
