mutation MeltToken($appId: Int!, $tokenId: String!, $value: Int!) {
  transaction: CreateEnjinRequest(type: MELT, appId: $appId, melt_token_data: {
    token_id: $tokenId,
    value: $value
  }) {
    id
    encodedData
    state
  }
}
