mutation MintNonFungibleItems($identityId: Int!, $tokenId: String!) {
  CreateEnjinRequest(
    identity_id: $identityId
    type: MINT
    mint_token_data: {
      token_id: $tokenId
      token_index: "0"
      recipient_address_array: [
        "WALLET_ADDRESS_1"
        "WALLET_ADDRESS_1"
        "WALLET_ADDRESS_1"
        "WALLET_ADDRESS_1"
        "WALLET_ADDRESS_1"
        "WALLET_ADDRESS_2"
        "WALLET_ADDRESS_2"
        "WALLET_ADDRESS_2"
      ]
    }
  ) {
    id
    encodedData
  }
}
