mutation SetItemUri($identityId: Int!, $tokenId: String!, $metadataUri: String!) {
  CreateEnjinRequest(
    identity_id: $identityId
    type: SET_ITEM_URI
    set_item_uri_data: {
      token_id: $tokenId
      token_index: 0
      item_uri: $metadataUri
    }
  ) {
    id
    encodedData
  }
}
