var hierarchy =
[
    [ "EnjinSDK.App", "class_enjin_s_d_k_1_1_app.html", null ],
    [ "HomeController.AppData", "class_home_controller_1_1_app_data.html", null ],
    [ "EnjinSDK.AppSelectorData", "class_enjin_s_d_k_1_1_app_selector_data.html", null ],
    [ "EnjinEditorPanel.CompoundQuery", "class_enjin_editor_panel_1_1_compound_query.html", null ],
    [ "PusherClient.Constants", "class_pusher_client_1_1_constants.html", null ],
    [ "EnjinSDK.CryptoItem", "class_enjin_s_d_k_1_1_crypto_item.html", null ],
    [ "EnjinEditorPanel.CryptoItemsController", "class_enjin_editor_panel_1_1_crypto_items_controller.html", null ],
    [ "CryptoItemsTab", "class_crypto_items_tab.html", null ],
    [ "CT_CreatePanel", "class_c_t___create_panel.html", null ],
    [ "CT_DetailsPane", "class_c_t___details_pane.html", null ],
    [ "CT_EditPanel", "class_c_t___edit_panel.html", null ],
    [ "CT_MainPanel", "class_c_t___main_panel.html", null ],
    [ "CT_MeltPanel", "class_c_t___melt_panel.html", null ],
    [ "CT_MintCostPane", "class_c_t___mint_cost_pane.html", null ],
    [ "CT_MintPanel", "class_c_t___mint_panel.html", null ],
    [ "CT_OptionsPane", "class_c_t___options_pane.html", null ],
    [ "CT_SearchPane", "class_c_t___search_pane.html", null ],
    [ "CT_ViewPanel", "class_c_t___view_panel.html", null ],
    [ "CT_WalletPane", "class_c_t___wallet_pane.html", null ],
    [ "EnjinSDK.Cursor", "class_enjin_s_d_k_1_1_cursor.html", null ],
    [ "DataFactoryHelper", "class_data_factory_helper.html", null ],
    [ "EnjinSDK.DateData", "class_enjin_s_d_k_1_1_date_data.html", null ],
    [ "DoxygenConfig", "class_doxygen_config.html", null ],
    [ "DoxyRunner", "class_doxy_runner.html", null ],
    [ "DoxyThreadSafeOutput", "class_doxy_thread_safe_output.html", null ],
    [ "EditorWindow", null, [
      [ "DoxygenWindow", "class_doxygen_window.html", null ],
      [ "EnjinEditorWindow", "class_enjin_editor_window.html", null ]
    ] ],
    [ "EnjinSDK.Enjin", "class_enjin_s_d_k_1_1_enjin.html", null ],
    [ "EnjinSDK.EnjinCryptoItems", "class_enjin_s_d_k_1_1_enjin_crypto_items.html", null ],
    [ "EnjinEditorPanel.EnjinEditor", "class_enjin_editor_panel_1_1_enjin_editor.html", null ],
    [ "EnjinSDK.EnjinEventManager", "class_enjin_s_d_k_1_1_enjin_event_manager.html", null ],
    [ "EnjinSDK.Helpers.EnjinHelpers", "class_enjin_s_d_k_1_1_helpers_1_1_enjin_helpers.html", null ],
    [ "EnjinSDK.Helpers.EnjinHelpers< T >", "class_enjin_s_d_k_1_1_helpers_1_1_enjin_helpers.html", null ],
    [ "EnjinSDK.EnjinIdentities", "class_enjin_s_d_k_1_1_enjin_identities.html", null ],
    [ "EnjinSDK.EnjinPlatform", "class_enjin_s_d_k_1_1_enjin_platform.html", null ],
    [ "EnjinSDK.EnjinRequests", "class_enjin_s_d_k_1_1_enjin_requests.html", null ],
    [ "EnjinSDK.EnjinUsers", "class_enjin_s_d_k_1_1_enjin_users.html", null ],
    [ "EnjinSDK.Errors", "class_enjin_s_d_k_1_1_errors.html", null ],
    [ "EnjinSDK.ErrorStatus", "class_enjin_s_d_k_1_1_error_status.html", null ],
    [ "PusherClient.EventEmitter", "class_pusher_client_1_1_event_emitter.html", [
      [ "PusherClient.Channel", "class_pusher_client_1_1_channel.html", [
        [ "PusherClient.PrivateChannel", "class_pusher_client_1_1_private_channel.html", [
          [ "PusherClient.PresenceChannel", "class_pusher_client_1_1_presence_channel.html", null ]
        ] ]
      ] ],
      [ "PusherClient.Pusher", "class_pusher_client_1_1_pusher.html", null ]
    ] ],
    [ "Exception", null, [
      [ "PusherClient.PusherException", "class_pusher_client_1_1_pusher_exception.html", null ]
    ] ],
    [ "Extensions", "class_extensions.html", null ],
    [ "EnjinSDK.Fields", "class_enjin_s_d_k_1_1_fields.html", null ],
    [ "EnjinSDK.FieldsResult", "class_enjin_s_d_k_1_1_fields_result.html", null ],
    [ "EnjinSDK.GraphQLTemplate", "class_enjin_s_d_k_1_1_graph_q_l_template.html", null ],
    [ "HomeController", "class_home_controller.html", null ],
    [ "HomeTab", "class_home_tab.html", null ],
    [ "HT_LoggedInPanel", "class_h_t___logged_in_panel.html", null ],
    [ "HT_LogininPanel", "class_h_t___loginin_panel.html", null ],
    [ "HT_ManageAppPanel", "class_h_t___manage_app_panel.html", null ],
    [ "HT_NewsPanel", "class_h_t___news_panel.html", null ],
    [ "HT_PlatformPanel", "class_h_t___platform_panel.html", null ],
    [ "HT_SupportPane", "class_h_t___support_pane.html", null ],
    [ "HT_ViewPanel", "class_h_t___view_panel.html", null ],
    [ "PusherClient.IAuthorizer", "interface_pusher_client_1_1_i_authorizer.html", [
      [ "PusherClient.HttpAuthorizer", "class_pusher_client_1_1_http_authorizer.html", null ]
    ] ],
    [ "IdentitiesTab", "class_identities_tab.html", null ],
    [ "IdentitiesTabController", "class_identities_tab_controller.html", null ],
    [ "EnjinSDK.Identity", "class_enjin_s_d_k_1_1_identity.html", null ],
    [ "EnjinSDK.IdFieldObject", "class_enjin_s_d_k_1_1_id_field_object.html", null ],
    [ "IEnumerable", null, [
      [ "SimpleJSON.JSONArray", "class_simple_j_s_o_n_1_1_j_s_o_n_array.html", null ],
      [ "SimpleJSON.JSONObject", "class_simple_j_s_o_n_1_1_j_s_o_n_object.html", null ]
    ] ],
    [ "IT_CreateEditPane", "class_i_t___create_edit_pane.html", null ],
    [ "IT_ListPane", "class_i_t___list_pane.html", null ],
    [ "IT_OptionsPanel", "class_i_t___options_panel.html", null ],
    [ "IT_SearchPanel", "class_i_t___search_panel.html", null ],
    [ "SimpleJSON.JSON", "class_simple_j_s_o_n_1_1_j_s_o_n.html", null ],
    [ "MiniJSON.Json", "class_mini_j_s_o_n_1_1_json.html", null ],
    [ "EnjinSDK.JSONArrayHelper< T >", "class_enjin_s_d_k_1_1_j_s_o_n_array_helper.html", null ],
    [ "JsonHelper", "class_json_helper.html", null ],
    [ "SimpleJSON.JSONNode", "class_simple_j_s_o_n_1_1_j_s_o_n_node.html", [
      [ "SimpleJSON.JSONArray", "class_simple_j_s_o_n_1_1_j_s_o_n_array.html", null ],
      [ "SimpleJSON.JSONBool", "class_simple_j_s_o_n_1_1_j_s_o_n_bool.html", null ],
      [ "SimpleJSON.JSONNull", "class_simple_j_s_o_n_1_1_j_s_o_n_null.html", null ],
      [ "SimpleJSON.JSONNumber", "class_simple_j_s_o_n_1_1_j_s_o_n_number.html", null ],
      [ "SimpleJSON.JSONObject", "class_simple_j_s_o_n_1_1_j_s_o_n_object.html", null ],
      [ "SimpleJSON.JSONString", "class_simple_j_s_o_n_1_1_j_s_o_n_string.html", null ]
    ] ],
    [ "HomeController.LoginCredentials", "class_home_controller_1_1_login_credentials.html", null ],
    [ "MiniJsonExtensions", "class_mini_json_extensions.html", null ],
    [ "EnjinSDK.Mobile", "class_enjin_s_d_k_1_1_mobile.html", null ],
    [ "MonoBehaviour", null, [
      [ "GraphQLClient.GraphQuery", "class_graph_q_l_client_1_1_graph_query.html", null ],
      [ "IconLoader", "class_icon_loader.html", null ],
      [ "TestSuite", "class_test_suite.html", null ]
    ] ],
    [ "EnjinSDK.News", "class_enjin_s_d_k_1_1_news.html", null ],
    [ "EnjinSDK.NewsResult", "class_enjin_s_d_k_1_1_news_result.html", null ],
    [ "NotificationMonitor", "class_notification_monitor.html", null ],
    [ "EnjinSDK.Notifications", "class_enjin_s_d_k_1_1_notifications.html", null ],
    [ "EnjinSDK.PaginationHelper< T >", "class_enjin_s_d_k_1_1_pagination_helper.html", null ],
    [ "EnjinSDK.Permissions", "class_enjin_s_d_k_1_1_permissions.html", null ],
    [ "EnjinSDK.Platform", "class_enjin_s_d_k_1_1_platform.html", null ],
    [ "EnjinSDK.PlatformInfo", "class_enjin_s_d_k_1_1_platform_info.html", null ],
    [ "EnjinSDK.PlatformOptions", "class_enjin_s_d_k_1_1_platform_options.html", null ],
    [ "PusherClient.PusherOptions", "class_pusher_client_1_1_pusher_options.html", null ],
    [ "PusherSettings", "class_pusher_settings.html", null ],
    [ "GraphQLClient.GraphQuery.Query", "class_graph_q_l_client_1_1_graph_query_1_1_query.html", null ],
    [ "EnjinSDK.Recipient", "class_enjin_s_d_k_1_1_recipient.html", null ],
    [ "EnjinSDK.Request", "class_enjin_s_d_k_1_1_request.html", null ],
    [ "EnjinSDK.RequestEvent", "class_enjin_s_d_k_1_1_request_event.html", null ],
    [ "EnjinSDK.RequestEventData", "class_enjin_s_d_k_1_1_request_event_data.html", null ],
    [ "EnjinEditorPanel.Result", "class_enjin_editor_panel_1_1_result.html", null ],
    [ "IdentitiesTabController.Result", "class_identities_tab_controller_1_1_result.html", null ],
    [ "EnjinSDK.Roles", "class_enjin_s_d_k_1_1_roles.html", null ],
    [ "EnjinSDK.SDK", "class_enjin_s_d_k_1_1_s_d_k.html", null ],
    [ "SearchPanel", "class_search_panel.html", null ],
    [ "SettingsController", "class_settings_controller.html", null ],
    [ "SettingsTab", "class_settings_tab.html", null ],
    [ "ST_FieldsPanel", "class_s_t___fields_panel.html", null ],
    [ "ST_GeneralPanel", "class_s_t___general_panel.html", null ],
    [ "ST_ItemsPanel", "class_s_t___items_panel.html", null ],
    [ "TeamController", "class_team_controller.html", null ],
    [ "TeamTab", "class_team_tab.html", null ],
    [ "EnjinSDK.TokenBalanceEntry", "class_enjin_s_d_k_1_1_token_balance_entry.html", null ],
    [ "EnjinSDK.TokenValueInputData", "class_enjin_s_d_k_1_1_token_value_input_data.html", null ],
    [ "EnjinSDK.TransferFeeSettings", "class_enjin_s_d_k_1_1_transfer_fee_settings.html", null ],
    [ "EnjinSDK.TransferRequest", "class_enjin_s_d_k_1_1_transfer_request.html", null ],
    [ "TT_ListPanel", "class_t_t___list_panel.html", null ],
    [ "TT_MemberPanel", "class_t_t___member_panel.html", null ],
    [ "TT_OptionsPanel", "class_t_t___options_panel.html", null ],
    [ "TT_PermissionsPanel", "class_t_t___permissions_panel.html", null ],
    [ "TT_RolesListPanel", "class_t_t___roles_list_panel.html", null ],
    [ "TT_RolesPanels", "class_t_t___roles_panels.html", null ],
    [ "EnjinSDK.User", "class_enjin_s_d_k_1_1_user.html", null ],
    [ "EnjinSDK.Identity.User", "class_enjin_s_d_k_1_1_identity_1_1_user.html", null ],
    [ "EnjinSDK.UserCredentials", "class_enjin_s_d_k_1_1_user_credentials.html", null ],
    [ "EnjinSDK.UserExists", "class_enjin_s_d_k_1_1_user_exists.html", null ],
    [ "WalletTab", "class_wallet_tab.html", null ]
];